package com.j3s.yobuddy.domain.notification.entity;

public enum NotificationType {
    TASK, KPI, MENTORING, SYSTEM, FORM,
    ONLINE_DUE_NEXT_WEEK,
    OFFLINE_NEXT_WEEK,
    ONLINE_DUE_TOMORROW,
    OFFLINE_FORM_PENDING,
    NEW_TRAINING,
    OFFLINE_TOMORROW,
    WEEKLY_REPORT_DUE_TODAY,
    WEEKLY_REPORT_FEEDBACK,
    NEW_ANNOUNCEMENT,
    TRAINING_ATTACHMENT_ADDED,
    TASK_DUE_NEXT_WEEK,
    TASK_DUE_TOMORROW,
    TASK_GRADED,
    MENTORING_SESSION_TODAY,
    NEW_PROGRAM_TASK,
    MENTOR_WEEKLY_REPORT_SUBMITTED,
    MENTOR_MENTORING_TODAY,
    MENTOR_TASK_SUBMITTED,
    MENTOR_WEEKLY_REPORT_FEEDBACK_DUE,
    ADMIN_OFFLINE_NEXT_WEEK,
    ADMIN_OFFLINE_TOMORROW
}
